export const START_LOADING_COMEDY = 'START_LOADING_COMEDY';
export const SET_COMEDY = 'SET_COMEDY';
export const FINISH_LOADING_COMEDY = 'FINISH_LOADING_COMEDY';

export const START_LOADING_DRAMA = 'START_LOADING_DRAMA';
export const SET_DRAMA = 'SET_DRAMA';
export const FINISH_LOADING_DRAMA = 'FINISH_LOADING_DRAMA';

export const START_LOADING_ACTION = 'START_LOADING_ACTION';
export const SET_ACTION = 'SET_ACTION';
export const FINISH_LOADING_ACTION = 'FINISH_LOADING_ACTION';

export const START_LOADING_POPULAR = 'START_LOADING_POPULAR';
export const SET_POPULAR = 'SET_POPULAR';
export const FINISH_LOADING_POPULAR = 'FINISH_LOADING_POPULAR';

export const START_LOADING_HORROR = 'START_LOADING_HORROR';
export const SET_HORROR = 'SET_HORROR';
export const FINISH_LOADING_HORROR = 'FINISH_LOADING_HORROR';

export const FINISH_LOADING_LOGIN = 'FINISH_LOADING_LOGIN';
export const SET_SUCCESS_LOGIN = 'SET_SUCCESS_LOGIN';
export const START_LOADING_LOGIN = 'START_LOADING_LOGIN';

export const CLOSE_SESSION = 'CLOSE_SESSION';